/**
 * Kapsel Agent Contract Types
 * Corresponds to §8 of the Kapsel Protocol Specification
 */

import type { TaskSummary, Task, TaskStep, VerificationResult } from './tasks.js';
import type { KapselSDK } from './sdk.js';

export type OneWayDoorType =
  | 'schema_migration'
  | 'public_api_change'
  | 'resource_deletion'
  | 'service_restart'
  | 'data_write'
  | 'external_publish';

export type EscalationReason =
  | 'wall_clock_exceeded'
  | 'step_failed_max_retries'
  | 'confirmation_expired'
  | 'tool_error_unrecoverable'
  | 'low_confidence'
  | 'user_blocked';

export interface OneWayDoor {
  stepIndex: number;
  type: OneWayDoorType;
  description: string;
  /** Generated by host, not agent */
  confirmationCode?: string;
}

export interface PlanStep {
  index: number;
  description: string;
  /** Tools this step will invoke. Host pre-validates existence. */
  tools: string[];
  dependsOnPrevious: boolean;
  isOneWayDoor: boolean;
}

export interface Plan {
  /**
   * Monotonically increasing version. Starts at 1.
   * Incremented each time the agent re-plans mid-execution.
   * Host uses this to avoid replaying already-completed steps.
   */
  version: number;
  /** Agent's restatement of the goal. Sent to user before execution. */
  goalRestatement: string;
  steps: PlanStep[];
  estimatedMs?: number;
  /** Overall plan confidence 0.0–1.0 */
  confidence: number;
  oneWayDoors: OneWayDoor[];
  risks?: string[];
}

export interface ToolCall {
  toolName: string;
  params: unknown;
  result: unknown;
  durationMs: number;
  success: boolean;
  error?: string;
}

export interface StepResult {
  stepIndex: number;
  success: boolean;
  /** Max 200 tokens */
  summary: string;
  toolCalls: ToolCall[];
  output?: unknown;
  /** Whether execution can proceed to the next step */
  canContinue: boolean;
  /** Required when canContinue is false. Explains why execution was halted. */
  blockedReason?: string;
}

export interface ShouldActivateResult {
  activate: boolean;
  /** 0.0–1.0 */
  confidence: number;
  reason?: string;
}

export interface EscalationResponse {
  retry: boolean;
  recoveryPlan?: Plan;
}

/**
 * Interface that agent extensions must implement.
 * All methods are called by the host via the message protocol.
 */
export interface AgentExtension {
  activate(sdk: KapselSDK): Promise<void>;
  /** Must respond within 5 seconds */
  shouldActivate(task: TaskSummary, sdk: KapselSDK): Promise<ShouldActivateResult>;
  /** Must respond within 30 seconds */
  plan(task: Task, sdk: KapselSDK): Promise<Plan>;
  executeStep(task: Task, plan: Plan, stepIndex: number, sdk: KapselSDK): Promise<StepResult>;
  /** Optional. If not implemented, host applies default verification. */
  verifyStep?(task: Task, step: TaskStep, sdk: KapselSDK): Promise<VerificationResult>;
  /** Optional. Called when a task is escalated. */
  onEscalation?(task: Task, reason: EscalationReason, sdk: KapselSDK): Promise<EscalationResponse>;
  /** Optional. Called on graceful shutdown. */
  deactivate?(): Promise<void>;
}
